#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""Render the bitmap font to a C header (assets/fonts/): Terminus 8x16 (BDF, SIL OFL 1.1).
One set of glyphs, drawn by gfx.c at two sizes:
  S  labels / units / status   1x, ASCII 32..126
  L  large values / titles     2x (pixel doubled), 32..95: lower case folds to upper case
plus the Latin-1 U-umlaut (HÜGELTON) for S; any other byte draws as '?'.

Glyph format: 16 rows of one byte, top to bottom, bit 7 = the leftmost pixel; the
advance is the cell width (8, 16 at 2x).
"""
import sys
from pathlib import Path

FONTS = Path(__file__).resolve().parents[1] / "assets" / "fonts"
BDF = "ter-u16n.bdf"
FIRST, LAST = 32, 126
EXTRA = [0xDC]                                         # Ü: glyph LAST - FIRST + 1 (FONT_UUML_GLYPH)


def render_bdf(path):
    """BDF bitmap font (Terminus 8x16): exact pixels, cell = the font bounding box."""
    lines = path.read_text(errors="replace").splitlines()
    fbb = next(l for l in lines if l.startswith("FONTBOUNDINGBOX")).split()
    cw, ch, fx, fy = int(fbb[1]), int(fbb[2]), int(fbb[3]), int(fbb[4])
    assert (cw, ch) == (8, 16)
    base = ch + fy                                     # rows above the baseline
    glyphs, i = {}, 0
    while i < len(lines):
        if lines[i].startswith("ENCODING"):
            code = int(lines[i].split()[1])
            j = i
            while not lines[j].startswith("BBX"):
                j += 1
            bw, bh, bx, by = map(int, lines[j].split()[1:5])
            dw = cw
            k = i
            while not lines[k].startswith("BITMAP"):
                if lines[k].startswith("DWIDTH"):
                    dw = int(lines[k].split()[1])
                k += 1
            rows = [int(r, 16) for r in lines[k + 1:k + 1 + bh]]
            nbits = ((bw + 7) // 8) * 8
            cell = [0] * (cw * ch)
            top = base - (by + bh)
            for r, bits in enumerate(rows):
                for c in range(bw):
                    if bits >> (nbits - 1 - c) & 1:
                        x, y = bx + c, top + r
                        if 0 <= x < cw and 0 <= y < ch:
                            cell[y * cw + x] = 1
            glyphs[code] = (dw, cell)
            i = k + bh
        i += 1
    if 0xDC not in glyphs and ord("U") in glyphs:      # Ü for "HÜGELTON": U with dots on its top row
        dw, cell = glyphs[ord("U")]
        cell = cell[:]
        lit = [x for y in range(ch) for x in range(cw) if cell[y * cw + x]]
        if lit:
            top = min(y for y in range(ch) for x in range(cw) if cell[y * cw + x])
            for x in range(cw):
                cell[top * cw + x] = 1 if x in (min(lit), max(lit)) else 0
            for x in range(cw):
                cell[(top + 1) * cw + x] = 0
            glyphs[0xDC] = (dw, cell)
    missing = [chr(c) for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        print(f"font {path.name}: no glyph for {''.join(missing)!r} (drawn as '?')")
    out = []
    for c in list(range(FIRST, LAST + 1)) + EXTRA:
        dw, cell = glyphs.get(c, glyphs[ord("?")])
        assert dw == cw, f"font {path.name}: {c} is not {cw} wide"
        out += [sum(cell[y * cw + x] << (7 - x) for x in range(cw)) for y in range(ch)]
    return out


def main(out):
    data = render_bdf(FONTS / BDF)
    lines = [f"/* generated by tools/gen_font.py from {BDF} */", "#pragma once", "#include <stdint.h>",
             f"#define FONT_UUML_GLYPH {LAST - FIRST + 1}  /* the Latin-1 U-umlaut */", "",
             f"static const uint8_t FONT_BITS[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines += ["};",
              f"static const felucca_font_t FONT_S = {{16, 1, {LAST}}};   /* labels / units / status */",
              "static const felucca_font_t FONT_L = {32, 2, 95};    /* large values / titles: capitals */", ""]
    print(f"font: {BDF} 8x16, {len(data) // 16} glyphs, {len(data)} B (S 1x, L 2x)")
    Path(out).write_text("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1])
